phrases = [
    "I can't believe you did that!",
    "Why does this always happen to me?",
    "I’m so tired of this nonsense!",
    "You’ve crossed the line this time!",
    "That was completely unacceptable!",
    "I can’t stand this anymore!",
    "This is absolutely ridiculous!",
    "You never listen to me!",
    "I’ve had enough of your excuses!",
    "Why can't you just be honest?",
    "This is getting out of hand!",
    "I am so fed up with this!",
    "You always do this to me!",
    "I don’t deserve to be treated like this!",
    "I’m losing my patience!",
    "How many times do I have to tell you?",
    "This is infuriating!",
    "You’ve really disappointed me this time!",
    "Why can't you take responsibility?",
    "I can't believe you lied to me!",
    "I'm so frustrated right now!",
    "That was incredibly selfish of you!",
    "I feel so disrespected!",
    "This has gone too far!",
    "You really hurt me this time!",
    "I can’t keep dealing with this!",
    "How could you do this to me?",
    "I am so mad right now!",
    "That was completely uncalled for!",
    "You never think about anyone but yourself!",
    "Why don’t you ever listen?",
    "I can’t believe you’re acting this way!",
    "You always put yourself first!",
    "I'm not going to put up with this anymore!",
    "You’ve pushed me too far!",
    "This is beyond frustrating!",
    "I don’t have time for this nonsense!",
    "Why do you always make everything so difficult?",
    "I’m done with your games!",
    "You make everything harder than it needs to be!",
    "I feel completely betrayed!",
    "You need to grow up!",
    "I am so angry I can't even speak!",
    "Why do you always have to make a scene?",
    "I can’t handle this level of disrespect!",
    "I am not okay with this!",
    "You’ve really crossed the line!",
    "I don’t understand why you keep doing this!",
    "This is absolutely infuriating!",
    "You are so inconsiderate!",
    "I am not going to tolerate this anymore!",
    "You’ve got some nerve!",
    "I can’t believe you thought that was okay!",
    "I’m so tired of your attitude!",
    "I’m at my breaking point!",
    "I am beyond angry right now!",
    "Why do you keep making the same mistakes?",
    "You never take anything seriously!",
    "I am furious with you!",
    "This is not how you treat someone!",
    "I can’t believe how rude you are!",
    "You have no idea how much you've upset me!",
    "I’m done being nice about this!",
    "You always find a way to ruin things!",
    "I’m tired of being taken for granted!",
    "You really let me down!",
    "I’ve had enough of your behavior!",
    "You’ve pushed me past my limit!",
    "I’m so annoyed right now!",
    "You never seem to care about my feelings!",
    "You’ve really messed things up this time!",
    "I can’t take this anymore!",
    "How could you be so thoughtless?",
    "I can't believe you ignored me!",
    "I am not happy with this situation!",
    "You always twist things around!",
    "You’ve gone too far this time!",
    "This is completely unacceptable!",
    "I’m tired of your lies!",
    "You have no respect for me!",
    "I can't believe you did that to me!",
    "You always think you're right!",
    "I’m losing my patience with you!",
    "You never admit when you're wrong!",
    "I am absolutely livid!",
    "I can’t believe how childish you’re being!",
    "Why can’t you just act like an adult?",
    "I am done with your nonsense!",
    "You always make excuses!",
    "I'm so angry I can't even think straight!",
    "You have crossed the final line!",
    "I feel so let down by you!",
    "I can’t believe you’re being this selfish!",
    "You never seem to care about anyone but yourself!",
    "I’m not putting up with this any longer!",
    "You’ve made me so angry I can’t even look at you!",
    "I am not going to stay quiet anymore!",
    "You always make everything about yourself!",
    "You’ve really pushed my buttons this time!",
    "I am so sick of your behavior!"
]


synonyms = ["angry", "furious", "irate", "enraged", "mad", "infuriated"]
