phrases = [
    "I actually cleared my driving test finally!",
    "I just found my favorite shirt on sale!",
    "I got the job I’ve been hoping for!",
    "Wow, the traffic today was light, got here so fast!",
    "I finally finished that book I’ve been reading forever!",
    "The weather is perfect for a walk today!",
    "I made it on time despite all the chaos!",
    "I found a new coffee place that’s amazing!",
    "I finally got all my laundry done!",
    "I managed to cook a perfect meal today!",
    "The weekend is finally here!",
    "I actually remembered all my errands today!",
    "I got a full eight hours of sleep last night!",
    "I caught the bus just before it left!",
    "I finally reached my savings goal!",
    "My favorite song came on the radio at just the right time!",
    "I got upgraded to first class, totally unexpected!",
    "My plants are actually thriving for once!",
    "The project I worked on was approved without changes!",
    "I found a parking spot right in front of the store!",
    "I was able to reunite with an old friend today!",
    "I tried a new recipe and it turned out delicious!",
    "I finally got my closet organized the way I wanted!",
    "The movie I’ve been waiting for is finally out!",
    "I got a surprise bonus at work today!",
    "I managed to get all my work done early!",
    "I just got complimented on my outfit!",
    "I found a great show to binge-watch!",
    "I fixed the sink all by myself!",
    "The rain stopped just as I stepped outside!",
    "My cat finally used the new bed I bought!",
    "I managed to wake up before the alarm!",
    "My favorite bakery had my favorite pastry today!",
    "I finished my workout and actually feel amazing!",
    "I got a great deal on something I needed!",
    "I made someone smile today!",
    "I finally beat that level in my game!",
    "I had the best coffee of my life this morning!",
    "The sunrise was gorgeous today!",
    "I finished my to-do list without feeling rushed!",
    "I caught up with my friend after so long!",
    "I finally learned how to solve that tricky problem!",
    "I got a great haircut this time!",
    "I made it to the gym today, feeling so proud!",
    "I just realized how much I’ve grown recently!",
    "I got an unexpected compliment from a stranger!",
    "I baked cookies, and they taste great!",
    "I found some old photos that made me smile!",
    "I remembered all the lyrics to my favorite song!",
    "I managed to stay calm in a tough situation!",
    "My boss appreciated my work today!",
    "I found an extra chocolate bar I forgot about!",
    "I finally sorted through my emails!",
    "I went for a walk and it was so relaxing!",
    "My new plant is sprouting new leaves!",
    "I got all green lights on the way here!",
    "I made it through the entire day without spilling coffee!",
    "I treated myself to a nice dessert today!",
    "I figured out a problem I was stuck on!",
    "The sunset looked amazing tonight!",
    "I received a handwritten letter from a friend!",
    "I got my favorite seat at the coffee shop!",
    "I actually had time to meditate today!",
    "I made someone laugh at work today!",
    "My favorite shirt still fits me perfectly!",
    "I learned something new and it feels great!",
    "The power stayed on during the storm!",
    "I remembered an important date without checking!",
    "I got my favorite pizza topping combo!",
    "I managed to say no to something that wasn’t right!",
    "My plants are blooming, and it makes me so happy!",
    "I received a thank-you note from a colleague!",
    "I found a lost earring under the couch!",
    "The Wi-Fi worked perfectly today!",
    "I took a nap, and it was just what I needed!",
    "I finished my book and loved every page!",
    "I managed to fix that broken drawer!",
    "I found the perfect gift for my friend!",
    "The customer service rep was so helpful!",
    "I had the house to myself for a few hours!",
    "I saw a beautiful rainbow today!",
    "My favorite snack was on sale at the store!",
    "I finally went on that hike I’ve been planning!",
    "I had a really good conversation with a neighbor!",
    "I just realized how much progress I’ve made!",
    "My coffee stayed warm until I finished it!",
    "I stayed in bed a little longer and it felt so good!",
    "My favorite show was renewed for another season!",
    "I remembered to take out the trash before it piled up!",
    "My favorite flowers are in bloom right now!",
    "I got through a challenging workout!",
    "I fixed something around the house all by myself!",
    "The store had just what I needed in stock!",
    "I finally went through that stack of papers!",
    "I got to pet a really cute dog today!",
    "I managed to get all my steps in today!",
    "I found a really interesting podcast episode!",
    "My recipe turned out better than I expected!",
    "I saw a cute animal video that made my day!",
    "I made a decision and feel confident about it!"
]

synonyms = ["happy", "joyful", "content", "cheerful", "pleased", "delighted"]
