phrases = [
    "I just feel so alone right now.",
    "I thought things would be different by now.",
    "I really miss how things used to be.",
    "I can't believe this happened to me.",
    "Everything feels pointless lately.",
    "I feel like I’m losing myself.",
    "I can’t stop thinking about how much I lost.",
    "I feel so disconnected from everyone.",
    "I wish I could just disappear for a while.",
    "It’s like no one really understands me.",
    "I'm tired of pretending everything is okay.",
    "I just don’t feel like myself anymore.",
    "I feel like I'm letting everyone down.",
    "It's hard to see the light at the end of the tunnel.",
    "I keep waiting for something good to happen, but it never does.",
    "I feel empty inside.",
    "I hate that I can’t do anything right.",
    "Nothing seems to make me happy anymore.",
    "I don’t even know who I am anymore.",
    "I feel like I'm a burden to everyone around me.",
    "Why does everything have to be so hard?",
    "I feel like I’m just going through the motions.",
    "I just wish I could be happy again.",
    "It hurts to even get out of bed some days.",
    "I feel like no matter what I do, it's never enough.",
    "I don’t have the energy to keep trying anymore.",
    "I feel like I’m always the one getting hurt.",
    "I don’t see the point in anything anymore.",
    "I just want this pain to stop.",
    "I wish things could go back to how they were before.",
    "I feel like I’m drowning in my own sadness.",
    "I can’t remember the last time I truly felt happy.",
    "Everything feels so heavy lately.",
    "It feels like everything is falling apart.",
    "I’m so tired of feeling like this all the time.",
    "I feel so forgotten by everyone.",
    "I just want to run away from everything.",
    "I can’t believe how much I've lost.",
    "I wish I could just escape from it all.",
    "I feel like I’ve failed at everything.",
    "I hate feeling like this, but I can’t help it.",
    "I just want to feel something other than this emptiness.",
    "I feel like my life has no purpose.",
    "I keep trying, but nothing ever changes.",
    "I feel so lost in my own mind.",
    "I just want to feel okay again.",
    "I feel like I'm always the one left behind.",
    "I hate that I'm always so sad.",
    "I just don’t know what to do anymore.",
    "I feel like I'm broken beyond repair.",
    "I wish I could just turn off my emotions.",
    "I feel like I’m not good enough for anyone.",
    "I hate waking up feeling this way every day.",
    "I feel like I’m always the one who cares more.",
    "It hurts to know I wasn’t enough.",
    "I just don’t see the point anymore.",
    "I feel like my heart is shattered into a million pieces.",
    "I feel like everyone is moving on without me.",
    "I can’t seem to shake this feeling of sadness.",
    "I hate that I can’t change anything.",
    "I feel like I’m losing everyone I care about.",
    "I just want to feel loved and understood.",
    "I hate feeling like I’m always the problem.",
    "I feel so disconnected from the person I used to be.",
    "I wish I could make things right again.",
    "I feel like my best is never good enough.",
    "I feel like I'm losing all hope.",
    "I just want someone to care about me for real.",
    "I feel like I'm slowly fading away.",
    "I can’t believe I let things get this bad.",
    "I feel like I’ve lost everything that mattered.",
    "I just want to feel like I belong somewhere.",
    "I feel like no one really needs me.",
    "I can’t stand feeling like this anymore.",
    "I feel like I’ve lost my way completely.",
    "I just wish I could stop feeling so sad.",
    "I feel like all my dreams are slipping away.",
    "I hate that I always end up hurt.",
    "I feel like I'm completely alone in this.",
    "I can’t remember the last time I felt genuinely happy.",
    "I feel like my life is falling apart before my eyes.",
    "I just wish I could be someone else for a while.",
    "I feel like I’m trapped in my own sadness.",
    "I hate that I can’t make myself happy.",
    "I feel like I’m always disappointing everyone.",
    "I just want this pain to end.",
    "I feel like I've lost all my motivation.",
    "I can’t help but feel like I’m a failure.",
    "I feel like my life has no direction.",
    "I hate that I can’t control how I feel.",
    "I feel like I’m slowly losing myself.",
    "I just want to feel normal again.",
    "I feel like everyone else is happy except me.",
    "I feel like I'm carrying the weight of the world.",
    "I wish I could just start over.",
    "I feel like I’m stuck in a never-ending cycle of sadness.",
    "I just want to feel like myself again.",
    "I hate that I’m always struggling.",
    "I feel like I have nothing left to give.",
    "I just wish someone would understand how I feel."
]

synonyms = ["sad", "crying", "heartbroken", "miserable", "on the verge of tears"]